const Constants = Object.freeze({
  MIN_ZOOM: 3,
  MAX_ZOOM: 20,

  LABELS_BELOW_ZINDEX: 2,
  BLUE_LINES_ZINDEX: 10,
  LABELS_ZINDEX: 50,
  MARKERS_ZINDEX: 51,

  LINE_OPACITY: 0.8,

  VECTOR_TRANSITION_LEVEL: 8,

  TILE_TRANSITION: 100,
});
export { Constants };
