// source: MuninViewState.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.MuninViewState', null, global);
goog.exportSymbol('proto.MuninViewState.CameraFrame', null, global);
goog.exportSymbol('proto.MuninViewState.LocationInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MuninViewState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MuninViewState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MuninViewState.displayName = 'proto.MuninViewState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MuninViewState.CameraFrame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MuninViewState.CameraFrame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MuninViewState.CameraFrame.displayName = 'proto.MuninViewState.CameraFrame';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MuninViewState.LocationInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MuninViewState.LocationInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MuninViewState.LocationInfo.displayName = 'proto.MuninViewState.LocationInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MuninViewState.prototype.toObject = function(opt_includeInstance) {
  return proto.MuninViewState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MuninViewState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MuninViewState.toObject = function(includeInstance, msg) {
  var f, obj = {
    cameraframe: (f = msg.getCameraframe()) && proto.MuninViewState.CameraFrame.toObject(includeInstance, f),
    locationinfo: (f = msg.getLocationinfo()) && proto.MuninViewState.LocationInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MuninViewState}
 */
proto.MuninViewState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MuninViewState;
  return proto.MuninViewState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MuninViewState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MuninViewState}
 */
proto.MuninViewState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MuninViewState.CameraFrame;
      reader.readMessage(value,proto.MuninViewState.CameraFrame.deserializeBinaryFromReader);
      msg.setCameraframe(value);
      break;
    case 2:
      var value = new proto.MuninViewState.LocationInfo;
      reader.readMessage(value,proto.MuninViewState.LocationInfo.deserializeBinaryFromReader);
      msg.setLocationinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MuninViewState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MuninViewState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MuninViewState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MuninViewState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCameraframe();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.MuninViewState.CameraFrame.serializeBinaryToWriter
    );
  }
  f = message.getLocationinfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.MuninViewState.LocationInfo.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MuninViewState.CameraFrame.prototype.toObject = function(opt_includeInstance) {
  return proto.MuninViewState.CameraFrame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MuninViewState.CameraFrame} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MuninViewState.CameraFrame.toObject = function(includeInstance, msg) {
  var f, obj = {
    latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    altitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    yaw: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    pitch: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    roll: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MuninViewState.CameraFrame}
 */
proto.MuninViewState.CameraFrame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MuninViewState.CameraFrame;
  return proto.MuninViewState.CameraFrame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MuninViewState.CameraFrame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MuninViewState.CameraFrame}
 */
proto.MuninViewState.CameraFrame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLatitude(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLongitude(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAltitude(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setYaw(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPitch(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRoll(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MuninViewState.CameraFrame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MuninViewState.CameraFrame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MuninViewState.CameraFrame} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MuninViewState.CameraFrame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatitude();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getAltitude();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getYaw();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getPitch();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getRoll();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
};


/**
 * optional double latitude = 1;
 * @return {number}
 */
proto.MuninViewState.CameraFrame.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.MuninViewState.CameraFrame} returns this
 */
proto.MuninViewState.CameraFrame.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double longitude = 2;
 * @return {number}
 */
proto.MuninViewState.CameraFrame.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.MuninViewState.CameraFrame} returns this
 */
proto.MuninViewState.CameraFrame.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double altitude = 3;
 * @return {number}
 */
proto.MuninViewState.CameraFrame.prototype.getAltitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.MuninViewState.CameraFrame} returns this
 */
proto.MuninViewState.CameraFrame.prototype.setAltitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double yaw = 4;
 * @return {number}
 */
proto.MuninViewState.CameraFrame.prototype.getYaw = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.MuninViewState.CameraFrame} returns this
 */
proto.MuninViewState.CameraFrame.prototype.setYaw = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double pitch = 5;
 * @return {number}
 */
proto.MuninViewState.CameraFrame.prototype.getPitch = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.MuninViewState.CameraFrame} returns this
 */
proto.MuninViewState.CameraFrame.prototype.setPitch = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double roll = 6;
 * @return {number}
 */
proto.MuninViewState.CameraFrame.prototype.getRoll = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.MuninViewState.CameraFrame} returns this
 */
proto.MuninViewState.CameraFrame.prototype.setRoll = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MuninViewState.LocationInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.MuninViewState.LocationInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MuninViewState.LocationInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MuninViewState.LocationInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    locationName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    secondaryLocationName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    localityName: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MuninViewState.LocationInfo}
 */
proto.MuninViewState.LocationInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MuninViewState.LocationInfo;
  return proto.MuninViewState.LocationInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MuninViewState.LocationInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MuninViewState.LocationInfo}
 */
proto.MuninViewState.LocationInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocationName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecondaryLocationName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocalityName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MuninViewState.LocationInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MuninViewState.LocationInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MuninViewState.LocationInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MuninViewState.LocationInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocationName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSecondaryLocationName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLocalityName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string location_name = 1;
 * @return {string}
 */
proto.MuninViewState.LocationInfo.prototype.getLocationName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.MuninViewState.LocationInfo} returns this
 */
proto.MuninViewState.LocationInfo.prototype.setLocationName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string secondary_location_name = 2;
 * @return {string}
 */
proto.MuninViewState.LocationInfo.prototype.getSecondaryLocationName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MuninViewState.LocationInfo} returns this
 */
proto.MuninViewState.LocationInfo.prototype.setSecondaryLocationName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string locality_name = 3;
 * @return {string}
 */
proto.MuninViewState.LocationInfo.prototype.getLocalityName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.MuninViewState.LocationInfo} returns this
 */
proto.MuninViewState.LocationInfo.prototype.setLocalityName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional CameraFrame cameraFrame = 1;
 * @return {?proto.MuninViewState.CameraFrame}
 */
proto.MuninViewState.prototype.getCameraframe = function() {
  return /** @type{?proto.MuninViewState.CameraFrame} */ (
    jspb.Message.getWrapperField(this, proto.MuninViewState.CameraFrame, 1));
};


/**
 * @param {?proto.MuninViewState.CameraFrame|undefined} value
 * @return {!proto.MuninViewState} returns this
*/
proto.MuninViewState.prototype.setCameraframe = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.MuninViewState} returns this
 */
proto.MuninViewState.prototype.clearCameraframe = function() {
  return this.setCameraframe(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MuninViewState.prototype.hasCameraframe = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional LocationInfo locationInfo = 2;
 * @return {?proto.MuninViewState.LocationInfo}
 */
proto.MuninViewState.prototype.getLocationinfo = function() {
  return /** @type{?proto.MuninViewState.LocationInfo} */ (
    jspb.Message.getWrapperField(this, proto.MuninViewState.LocationInfo, 2));
};


/**
 * @param {?proto.MuninViewState.LocationInfo|undefined} value
 * @return {!proto.MuninViewState} returns this
*/
proto.MuninViewState.prototype.setLocationinfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.MuninViewState} returns this
 */
proto.MuninViewState.prototype.clearLocationinfo = function() {
  return this.setLocationinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MuninViewState.prototype.hasLocationinfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
